### PR TITLE
spike: yaegi readline

### PR DESCRIPTION
**Pull request by gmarik**
A PR to gauge interest of adding a  `readline` or alike  functionality to the cli-command.
Note: code is a throwaway prototype to see how difficult it is to integrate [liner](https://github.com/peterh/liner): a compact `readline` implementation.

## problem
`yeagi` without common `readline`  functionality is a poor UX and may limit wider adoption.

## how: in action
1. `cd cmd/yaegi-readline/`
2. `go1.11 run ./`
3. enjoy: history, shortcuts, completion, etc…

## PS
met @emilevauge at the docker meetup  yesterday and he suggested going ahead and opening  a PR. Previously I thought you're not interested in adding any dependencies.

### CODE REVIEW

**Comment by ldez** [comment]
Hello,

Thanks, we don't want to introduce external dependencies

> Written in pure Go, using only the standard library

https://github.com/containous/yaegi#features

**Comment by gmarik** [comment]
> we don't want to introduce external dependencies.

IMO it's a case when having a dependency is justified, since:
0. efforts to re-implement from scratch are significant
0. it's a separate, terminal/leaf package: cli dependencies will not "pollute" the core
0. end user may choose whether to use `yaegi` or `yaegi-readline`

I'd love to do it but i'll take some time unless short-cuts are taken…

**Comment by emilevauge** [comment]
Hey @gmarik :)
Thanks for the PR, you were fast!
In fact, I think I suggested to create an issue before, in order to open the discussion, as I was not aware of any potential reason to not implement this.
@ldez I understand your statement, but can we try to find a consensus without rewriting everything (which, I hope you agree, does not make sense)?
IMHO, either we provide a rich REPL, either we don't provide anything.

**Comment by ldez** [comment]
In the future, I think we will split the yaegi core and the yaegi CLI/REPL as 2 projects.

When we will do that we will be able to use external dependencies.

For now, there are some side effects to add an external dependency.

The issue related #315.

**Comment by gmarik** [comment]
1. hey emile sorry i think i didnt catch the bit about the “issue”. either way my thinking was  a working prototype is better than “an idea” since there’s already one
2. imo splitting is unnecessary: library users will not depend on readline as long as it’s separated and isolated

let me know your thoughts

**Comment by mvertes** [comment]
As explained previously, for the moment we would like to avoid external dependencies, as we don't have any yet. We believe that a good advanced REPL could be built on top of yaegi in an external project.

Thanks.

**Pull request closed without merging**
